const productsData = [
  {
    id: 1,
    img: "/womentoner.png",
    name: "Heaven Dove Toner",
    price: 399,
    rating: 3.8,
    reviewCount: 4,
    brand: "Heaven Dove",
    concern: "Night Routine",
    createdAt: "2024-01-01",
    desc: "A gentle facial toner that helps tighten pores and refresh your skin.",
    box: "1 Toner Bottle (150 ml)",
    reviews: [
      { user: "Muskan", rating: 4, comment: "Very refreshing toner, loved it!" },
      { user: "Garima", rating: 3, comment: "Good but slightly drying for me." },
    ],
  },
  {
    id: 2,
    img: "/foundation.jpg",
    name: "Luminous Complexion Foundation",
    price: 499,
    rating: 4.5,
    reviewCount: 3,
    brand: "Luminous",
    concern: "Skin Brightening",
    createdAt: "2024-02-01",
    desc: "Provides smooth and flawless coverage with a natural glow.",
    box: "1 Foundation Bottle (30 ml)",
    reviews: [
      { user: "Asha", rating: 5, comment: "Perfect shade and long-lasting!" },
      { user: "Anuradha", rating: 4, comment: "Blends really well on skin." },
    ],
  },
  {
    id: 3,
    img: "/eyeliner.png",
    name: "Luron Eyeliner",
    price: 399,
    rating: 4.4,
    reviewCount: 2,
    brand: "Luron",
    concern: "Night Routine",
    createdAt: "2024-03-01",
    desc: "Highly pigmented eyeliner for bold and precise eye definition.",
    box: "1 Liquid Eyeliner Pen (5 ml)",
    reviews: [
      { user: "Mehak", rating: 5, comment: "Very sharp and easy to apply!" },
      { user: "Khushi", rating: 4, comment: "Stays all day without smudging." },
    ],
  },
  {
    id: 4,
    img: "/serum2.png",
    name: "Dr Rashel's Salicylic Acid 2% Face Serum",
    price: 349,
    rating: 2.4,
    reviewCount: 6,
    brand: "Dr Rashel",
    concern: "Anti Acne",
    createdAt: "2024-04-01",
    desc: "Helps reduce acne and unclog pores for clearer skin.",
    box: "1 Serum Dropper Bottle (30 ml)",
    reviews: [
      { user: "Bhavya", rating: 2, comment: "Did not work well for me." },
      { user: "Nitin", rating: 3, comment: "Average product, slow results." },
    ],
  },
  {
    id: 5,
    img: "/facewashmen.png",
    name: "Nivea Face Wash for Men",
    price: 299,
    rating: 4.2,
    reviewCount: 5,
    brand: "Nivea",
    concern: "Oil Control",
    createdAt: "2024-05-01",
    desc: "Deep cleans dirt and oil while keeping skin fresh and energized.",
    box: "1 Face Wash Tube (100 ml)",
    reviews: [
      { user: "Sushant", rating: 5, comment: "Very refreshing and cooling effect!" },
      { user: "Saksham", rating: 4, comment: "Good for daily use." },
    ],
  },
];

export default productsData;